import { FiUser } from 'react-icons/fi';
import { IoExitOutline } from 'react-icons/io5';
import { BsBookmark } from 'react-icons/bs';

function generateRandomChartData(size: number) {
  let labels = [];
  let data = [];

  for (let i = 0; i <= size; i++) {
    labels.push('');
    data.push(Math.round(Math.random() * 10));
  }

  return {
    labels: labels,
    datasets: [
      {
        label: '',
        data: data,
        borderColor: '#FCC54C',
        backgroundColor: '#FCC54C',
      },
    ],
  };
}

function useMockData() {
  const AuthorsInstagram = [
    'https://www.instagram.com',
    'https://www.instagram.com',
    'https://www.instagram.com',
    'https://www.instagram.com',
    'https://www.instagram.com',
    'https://www.instagram.com',
    'https://www.instagram.com',
    'https://www.instagram.com',
    'https://www.instagram.com',
  ];

  const comments = [
    { author: 'comentator', text: 'hi my name is coment i am important' },
    {
      author: 'Andrew Johnson',
      text: 'hi my name is coment i am important not copired comment',
    },
    {
      author: 'Real Comentator',
      text: 'hi my name is coment i am important not copired comment 100% original',
    },
    {
      author: 'Andrew Piterson',
      text: 'sheeeesh',
    },
  ];
  const dropDowns = [
    { href: '/profile', icon: <FiUser size={20} />, text: 'Profile' },
    { href: '/profile/marked', icon: <BsBookmark size={20} />, text: 'Marked' },
    {
      href: '/api/auth/signout',
      icon: <IoExitOutline size={24} />,
      text: 'Exit',
    },
  ];
  const urls = [
    { href: '/', text: 'News Pulse' },
    { href: '/contact-us', text: 'Contact us' },
    { href: '/about-us', text: 'About us' },
  ];

  const categories = [
    'Food',
    'Animal',
    'Car',
    'Sport',
    'Music',
    'Technology',
    'Abstract',
    'Nature',
  ];
  const profileOptions = [
    { title: 'profile', href: '/profile' },
    { title: 'send post', href: '/profile/post' },
    { title: 'posts', href: '/profile/posts' },
  ];

  const members: MemberT[] = [
    { position: 'Designer', name: 'Behzad Pashaei' },
    { position: 'Programmer', name: 'Cassie Evans' },
    { position: 'Marketing', name: 'Louis Hoebregts' },
    { position: 'Administrative', name: 'Patricia' },
    { position: 'CEO', name: 'James Hoebregts' },
    { position: 'Financial', name: 'Jon Kantner' },
  ];
  const mockWeather: WeatherT = {
    location: {
      name: 'Lviv',
      region: '',
      country: 'Ukraine',
      lat: 49.83,
      lon: 24,
      tz_id: 'Europe/Kiev',
      localtime_epoch: 1696833309,
      localtime: '2023-10-09 9:35',
    },
    current: {
      last_updated_epoch: 1696833000,
      last_updated: '2023-10-09 09:30',
      temp_c: 5.6,
      temp_f: 42.1,
      is_day: 1,
      condition: {
        text: 'Overcast',
        icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
        code: 1009,
      },
      wind_mph: 13.2,
      wind_kph: 21.2,
      wind_degree: 282,
      wind_dir: 'WNW',
      pressure_mb: 1027,
      pressure_in: 30.33,
      precip_mm: 0,
      precip_in: 0,
      humidity: 55,
      cloud: 100,
      feelslike_c: 1.7,
      feelslike_f: 35,
      vis_km: 10,
      vis_miles: 6,
      uv: 2,
      gust_mph: 17.1,
      gust_kph: 27.5,
    },
    forecast: {
      forecastday: [
        {
          date: '2023-10-09',
          date_epoch: 1696809600,
          day: {
            maxtemp_c: 10.1,
            maxtemp_f: 50.2,
            mintemp_c: 2.5,
            mintemp_f: 36.6,
            avgtemp_c: 5.6,
            avgtemp_f: 42.1,
            maxwind_mph: 14.1,
            maxwind_kph: 22.7,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 51,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            uv: 3,
          },
          astro: {
            sunrise: '07:36 AM',
            sunset: '06:46 PM',
            moonrise: '01:22 AM',
            moonset: '05:25 PM',
            moon_phase: 'Waning Crescent',
            moon_illumination: '28',
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1696798800,
              time: '2023-10-09 00:00',
              temp_c: 5,
              temp_f: 40.9,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 11.9,
              wind_kph: 19.1,
              wind_degree: 300,
              wind_dir: 'WNW',
              pressure_mb: 1024,
              pressure_in: 30.24,
              precip_mm: 0,
              precip_in: 0,
              humidity: 50,
              cloud: 5,
              feelslike_c: 1.1,
              feelslike_f: 34,
              windchill_c: 1.1,
              windchill_f: 34,
              heatindex_c: 5,
              heatindex_f: 40.9,
              dewpoint_c: -4.5,
              dewpoint_f: 23.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.2,
              gust_kph: 32.6,
              uv: 1,
            },
            {
              time_epoch: 1696802400,
              time: '2023-10-09 01:00',
              temp_c: 4.2,
              temp_f: 39.6,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 11.4,
              wind_kph: 18.4,
              wind_degree: 298,
              wind_dir: 'WNW',
              pressure_mb: 1025,
              pressure_in: 30.26,
              precip_mm: 0,
              precip_in: 0,
              humidity: 54,
              cloud: 5,
              feelslike_c: 0.3,
              feelslike_f: 32.6,
              windchill_c: 0.3,
              windchill_f: 32.6,
              heatindex_c: 4.2,
              heatindex_f: 39.6,
              dewpoint_c: -4.3,
              dewpoint_f: 24.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20,
              gust_kph: 32.3,
              uv: 1,
            },
            {
              time_epoch: 1696806000,
              time: '2023-10-09 02:00',
              temp_c: 3.7,
              temp_f: 38.7,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 11.2,
              wind_kph: 18,
              wind_degree: 289,
              wind_dir: 'WNW',
              pressure_mb: 1025,
              pressure_in: 30.28,
              precip_mm: 0,
              precip_in: 0,
              humidity: 57,
              cloud: 6,
              feelslike_c: -0.3,
              feelslike_f: 31.4,
              windchill_c: -0.3,
              windchill_f: 31.4,
              heatindex_c: 3.7,
              heatindex_f: 38.7,
              dewpoint_c: -4,
              dewpoint_f: 24.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.6,
              gust_kph: 31.6,
              uv: 1,
            },
            {
              time_epoch: 1696809600,
              time: '2023-10-09 03:00',
              temp_c: 3.3,
              temp_f: 37.9,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 11.2,
              wind_kph: 18,
              wind_degree: 283,
              wind_dir: 'WNW',
              pressure_mb: 1026,
              pressure_in: 30.29,
              precip_mm: 0,
              precip_in: 0,
              humidity: 60,
              cloud: 7,
              feelslike_c: -0.9,
              feelslike_f: 30.5,
              windchill_c: -0.9,
              windchill_f: 30.5,
              heatindex_c: 3.3,
              heatindex_f: 37.9,
              dewpoint_c: -3.8,
              dewpoint_f: 25.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.6,
              gust_kph: 31.6,
              uv: 1,
            },
            {
              time_epoch: 1696813200,
              time: '2023-10-09 04:00',
              temp_c: 3.1,
              temp_f: 37.5,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 11.2,
              wind_kph: 18,
              wind_degree: 278,
              wind_dir: 'W',
              pressure_mb: 1026,
              pressure_in: 30.3,
              precip_mm: 0,
              precip_in: 0,
              humidity: 62,
              cloud: 15,
              feelslike_c: -1.1,
              feelslike_f: 30,
              windchill_c: -1.1,
              windchill_f: 30,
              heatindex_c: 3.1,
              heatindex_f: 37.5,
              dewpoint_c: -3.6,
              dewpoint_f: 25.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.2,
              gust_kph: 30.9,
              uv: 1,
            },
            {
              time_epoch: 1696816800,
              time: '2023-10-09 05:00',
              temp_c: 3,
              temp_f: 37.4,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 11,
              wind_kph: 17.6,
              wind_degree: 279,
              wind_dir: 'W',
              pressure_mb: 1026,
              pressure_in: 30.3,
              precip_mm: 0,
              precip_in: 0,
              humidity: 63,
              cloud: 46,
              feelslike_c: -1.1,
              feelslike_f: 30,
              windchill_c: -1.1,
              windchill_f: 30,
              heatindex_c: 3,
              heatindex_f: 37.4,
              dewpoint_c: -3.4,
              dewpoint_f: 25.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 18.6,
              gust_kph: 30,
              uv: 1,
            },
            {
              time_epoch: 1696820400,
              time: '2023-10-09 06:00',
              temp_c: 2.5,
              temp_f: 36.6,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 10.3,
              wind_kph: 16.6,
              wind_degree: 277,
              wind_dir: 'W',
              pressure_mb: 1026,
              pressure_in: 30.31,
              precip_mm: 0,
              precip_in: 0,
              humidity: 66,
              cloud: 48,
              feelslike_c: -1.5,
              feelslike_f: 29.2,
              windchill_c: -1.5,
              windchill_f: 29.2,
              heatindex_c: 2.5,
              heatindex_f: 36.6,
              dewpoint_c: -3.2,
              dewpoint_f: 26.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 18.4,
              gust_kph: 29.6,
              uv: 1,
            },
            {
              time_epoch: 1696824000,
              time: '2023-10-09 07:00',
              temp_c: 2.7,
              temp_f: 36.8,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 10.7,
              wind_kph: 17.3,
              wind_degree: 277,
              wind_dir: 'W',
              pressure_mb: 1027,
              pressure_in: 30.32,
              precip_mm: 0,
              precip_in: 0,
              humidity: 65,
              cloud: 60,
              feelslike_c: -1.5,
              feelslike_f: 29.4,
              windchill_c: -1.5,
              windchill_f: 29.4,
              heatindex_c: 2.7,
              heatindex_f: 36.8,
              dewpoint_c: -3.1,
              dewpoint_f: 26.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 18.5,
              gust_kph: 29.8,
              uv: 1,
            },
            {
              time_epoch: 1696827600,
              time: '2023-10-09 08:00',
              temp_c: 4.1,
              temp_f: 39.3,
              is_day: 1,
              condition: {
                text: 'Cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
                code: 1006,
              },
              wind_mph: 11.4,
              wind_kph: 18.4,
              wind_degree: 280,
              wind_dir: 'W',
              pressure_mb: 1027,
              pressure_in: 30.33,
              precip_mm: 0,
              precip_in: 0,
              humidity: 61,
              cloud: 63,
              feelslike_c: 0.1,
              feelslike_f: 32.2,
              windchill_c: 0.1,
              windchill_f: 32.2,
              heatindex_c: 4.1,
              heatindex_f: 39.3,
              dewpoint_c: -2.9,
              dewpoint_f: 26.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.5,
              gust_kph: 26.6,
              uv: 1,
            },
            {
              time_epoch: 1696831200,
              time: '2023-10-09 09:00',
              temp_c: 5.6,
              temp_f: 42.1,
              is_day: 1,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
                code: 1009,
              },
              wind_mph: 13.2,
              wind_kph: 21.2,
              wind_degree: 282,
              wind_dir: 'WNW',
              pressure_mb: 1027,
              pressure_in: 30.33,
              precip_mm: 0,
              precip_in: 0,
              humidity: 55,
              cloud: 100,
              feelslike_c: 1.7,
              feelslike_f: 35,
              windchill_c: 1.7,
              windchill_f: 35,
              heatindex_c: 5.6,
              heatindex_f: 42.1,
              dewpoint_c: -2.7,
              dewpoint_f: 27.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17.1,
              gust_kph: 27.5,
              uv: 2,
            },
            {
              time_epoch: 1696834800,
              time: '2023-10-09 10:00',
              temp_c: 6.9,
              temp_f: 44.4,
              is_day: 1,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
                code: 1009,
              },
              wind_mph: 14.1,
              wind_kph: 22.7,
              wind_degree: 283,
              wind_dir: 'WNW',
              pressure_mb: 1027,
              pressure_in: 30.33,
              precip_mm: 0,
              precip_in: 0,
              humidity: 50,
              cloud: 100,
              feelslike_c: 3.2,
              feelslike_f: 37.7,
              windchill_c: 3.2,
              windchill_f: 37.7,
              heatindex_c: 6.9,
              heatindex_f: 44.4,
              dewpoint_c: -2.7,
              dewpoint_f: 27.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17.1,
              gust_kph: 27.5,
              uv: 2,
            },
            {
              time_epoch: 1696838400,
              time: '2023-10-09 11:00',
              temp_c: 8,
              temp_f: 46.3,
              is_day: 1,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 14.1,
              wind_kph: 22.7,
              wind_degree: 285,
              wind_dir: 'WNW',
              pressure_mb: 1027,
              pressure_in: 30.32,
              precip_mm: 0,
              precip_in: 0,
              humidity: 45,
              cloud: 50,
              feelslike_c: 4.6,
              feelslike_f: 40.2,
              windchill_c: 4.6,
              windchill_f: 40.2,
              heatindex_c: 8,
              heatindex_f: 46.3,
              dewpoint_c: -3.2,
              dewpoint_f: 26.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.2,
              gust_kph: 26.1,
              uv: 3,
            },
            {
              time_epoch: 1696842000,
              time: '2023-10-09 12:00',
              temp_c: 9.1,
              temp_f: 48.5,
              is_day: 1,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 13.9,
              wind_kph: 22.3,
              wind_degree: 287,
              wind_dir: 'WNW',
              pressure_mb: 1027,
              pressure_in: 30.31,
              precip_mm: 0,
              precip_in: 0,
              humidity: 39,
              cloud: 23,
              feelslike_c: 6.1,
              feelslike_f: 42.9,
              windchill_c: 6.1,
              windchill_f: 42.9,
              heatindex_c: 9.2,
              heatindex_f: 48.5,
              dewpoint_c: -4.1,
              dewpoint_f: 24.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.9,
              gust_kph: 25.7,
              uv: 3,
            },
            {
              time_epoch: 1696845600,
              time: '2023-10-09 13:00',
              temp_c: 9.8,
              temp_f: 49.6,
              is_day: 1,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 13.6,
              wind_kph: 22,
              wind_degree: 286,
              wind_dir: 'WNW',
              pressure_mb: 1026,
              pressure_in: 30.29,
              precip_mm: 0,
              precip_in: 0,
              humidity: 35,
              cloud: 11,
              feelslike_c: 6.9,
              feelslike_f: 44.4,
              windchill_c: 6.9,
              windchill_f: 44.4,
              heatindex_c: 9.8,
              heatindex_f: 49.6,
              dewpoint_c: -4.9,
              dewpoint_f: 23.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.7,
              gust_kph: 25.3,
              uv: 3,
            },
            {
              time_epoch: 1696849200,
              time: '2023-10-09 14:00',
              temp_c: 10,
              temp_f: 50.1,
              is_day: 1,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 13.6,
              wind_kph: 22,
              wind_degree: 285,
              wind_dir: 'WNW',
              pressure_mb: 1025,
              pressure_in: 30.28,
              precip_mm: 0,
              precip_in: 0,
              humidity: 33,
              cloud: 14,
              feelslike_c: 7.2,
              feelslike_f: 45,
              windchill_c: 7.2,
              windchill_f: 45,
              heatindex_c: 10,
              heatindex_f: 50.1,
              dewpoint_c: -5.3,
              dewpoint_f: 22.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.7,
              gust_kph: 25.3,
              uv: 4,
            },
            {
              time_epoch: 1696852800,
              time: '2023-10-09 15:00',
              temp_c: 10.1,
              temp_f: 50.2,
              is_day: 1,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 13.6,
              wind_kph: 22,
              wind_degree: 285,
              wind_dir: 'WNW',
              pressure_mb: 1025,
              pressure_in: 30.26,
              precip_mm: 0,
              precip_in: 0,
              humidity: 33,
              cloud: 16,
              feelslike_c: 7.3,
              feelslike_f: 45.2,
              windchill_c: 7.3,
              windchill_f: 45.2,
              heatindex_c: 10.1,
              heatindex_f: 50.2,
              dewpoint_c: -5.5,
              dewpoint_f: 22.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.9,
              gust_kph: 25.6,
              uv: 4,
            },
            {
              time_epoch: 1696856400,
              time: '2023-10-09 16:00',
              temp_c: 9.6,
              temp_f: 49.3,
              is_day: 1,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 12.8,
              wind_kph: 20.5,
              wind_degree: 285,
              wind_dir: 'WNW',
              pressure_mb: 1024,
              pressure_in: 30.25,
              precip_mm: 0,
              precip_in: 0,
              humidity: 35,
              cloud: 12,
              feelslike_c: 6.9,
              feelslike_f: 44.4,
              windchill_c: 6.9,
              windchill_f: 44.4,
              heatindex_c: 9.6,
              heatindex_f: 49.4,
              dewpoint_c: -5.2,
              dewpoint_f: 22.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.7,
              gust_kph: 26.9,
              uv: 3,
            },
            {
              time_epoch: 1696860000,
              time: '2023-10-09 17:00',
              temp_c: 8.4,
              temp_f: 47.1,
              is_day: 1,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 275,
              wind_dir: 'W',
              pressure_mb: 1024,
              pressure_in: 30.25,
              precip_mm: 0,
              precip_in: 0,
              humidity: 40,
              cloud: 5,
              feelslike_c: 5.9,
              feelslike_f: 42.6,
              windchill_c: 5.9,
              windchill_f: 42.6,
              heatindex_c: 8.4,
              heatindex_f: 47.1,
              dewpoint_c: -4.3,
              dewpoint_f: 24.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.1,
              gust_kph: 24.3,
              uv: 3,
            },
            {
              time_epoch: 1696863600,
              time: '2023-10-09 18:00',
              temp_c: 5.5,
              temp_f: 41.9,
              is_day: 1,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 263,
              wind_dir: 'W',
              pressure_mb: 1025,
              pressure_in: 30.26,
              precip_mm: 0,
              precip_in: 0,
              humidity: 48,
              cloud: 3,
              feelslike_c: 2.9,
              feelslike_f: 37.2,
              windchill_c: 2.9,
              windchill_f: 37.2,
              heatindex_c: 5.5,
              heatindex_f: 41.9,
              dewpoint_c: -4.6,
              dewpoint_f: 23.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.5,
              gust_kph: 24.9,
              uv: 3,
            },
            {
              time_epoch: 1696867200,
              time: '2023-10-09 19:00',
              temp_c: 4.7,
              temp_f: 40.5,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 262,
              wind_dir: 'W',
              pressure_mb: 1025,
              pressure_in: 30.27,
              precip_mm: 0,
              precip_in: 0,
              humidity: 51,
              cloud: 1,
              feelslike_c: 2.1,
              feelslike_f: 35.8,
              windchill_c: 2.1,
              windchill_f: 35.8,
              heatindex_c: 4.7,
              heatindex_f: 40.5,
              dewpoint_c: -4.5,
              dewpoint_f: 23.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.6,
              gust_kph: 23.4,
              uv: 1,
            },
            {
              time_epoch: 1696870800,
              time: '2023-10-09 20:00',
              temp_c: 4.4,
              temp_f: 39.9,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 259,
              wind_dir: 'W',
              pressure_mb: 1025,
              pressure_in: 30.27,
              precip_mm: 0,
              precip_in: 0,
              humidity: 52,
              cloud: 1,
              feelslike_c: 1.7,
              feelslike_f: 35,
              windchill_c: 1.7,
              windchill_f: 35,
              heatindex_c: 4.4,
              heatindex_f: 39.9,
              dewpoint_c: -4.5,
              dewpoint_f: 23.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.6,
              gust_kph: 23.4,
              uv: 1,
            },
            {
              time_epoch: 1696874400,
              time: '2023-10-09 21:00',
              temp_c: 4,
              temp_f: 39.3,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 248,
              wind_dir: 'WSW',
              pressure_mb: 1025,
              pressure_in: 30.25,
              precip_mm: 0,
              precip_in: 0,
              humidity: 53,
              cloud: 32,
              feelslike_c: 1.4,
              feelslike_f: 34.5,
              windchill_c: 1.4,
              windchill_f: 34.5,
              heatindex_c: 4,
              heatindex_f: 39.3,
              dewpoint_c: -4.7,
              dewpoint_f: 23.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.6,
              gust_kph: 21.9,
              uv: 1,
            },
            {
              time_epoch: 1696878000,
              time: '2023-10-09 22:00',
              temp_c: 3.8,
              temp_f: 38.8,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 237,
              wind_dir: 'WSW',
              pressure_mb: 1024,
              pressure_in: 30.25,
              precip_mm: 0,
              precip_in: 0,
              humidity: 54,
              cloud: 3,
              feelslike_c: 1.1,
              feelslike_f: 34,
              windchill_c: 1.1,
              windchill_f: 34,
              heatindex_c: 3.8,
              heatindex_f: 38.8,
              dewpoint_c: -4.7,
              dewpoint_f: 23.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.6,
              gust_kph: 21.9,
              uv: 1,
            },
            {
              time_epoch: 1696881600,
              time: '2023-10-09 23:00',
              temp_c: 3.4,
              temp_f: 38.2,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 217,
              wind_dir: 'SW',
              pressure_mb: 1024,
              pressure_in: 30.23,
              precip_mm: 0,
              precip_in: 0,
              humidity: 55,
              cloud: 8,
              feelslike_c: 0.8,
              feelslike_f: 33.4,
              windchill_c: 0.8,
              windchill_f: 33.4,
              heatindex_c: 3.4,
              heatindex_f: 38.2,
              dewpoint_c: -4.7,
              dewpoint_f: 23.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.2,
              gust_kph: 21.2,
              uv: 1,
            },
          ],
        },
        {
          date: '2023-10-10',
          date_epoch: 1696896000,
          day: {
            maxtemp_c: 6.7,
            maxtemp_f: 44.1,
            mintemp_c: 3.6,
            mintemp_f: 38.5,
            avgtemp_c: 5.7,
            avgtemp_f: 42.2,
            maxwind_mph: 12.5,
            maxwind_kph: 20.2,
            totalprecip_mm: 2.32,
            totalprecip_in: 0.09,
            totalsnow_cm: 0,
            avgvis_km: 8,
            avgvis_miles: 4,
            avghumidity: 77,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 87,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            uv: 2,
          },
          astro: {
            sunrise: '07:37 AM',
            sunset: '06:44 PM',
            moonrise: '02:32 AM',
            moonset: '05:41 PM',
            moon_phase: 'Waning Crescent',
            moon_illumination: '20',
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1696885200,
              time: '2023-10-10 00:00',
              temp_c: 3.6,
              temp_f: 38.5,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 203,
              wind_dir: 'SSW',
              pressure_mb: 1023,
              pressure_in: 30.21,
              precip_mm: 0,
              precip_in: 0,
              humidity: 54,
              cloud: 9,
              feelslike_c: 1.2,
              feelslike_f: 34.1,
              windchill_c: 1.2,
              windchill_f: 34.1,
              heatindex_c: 3.6,
              heatindex_f: 38.5,
              dewpoint_c: -4.7,
              dewpoint_f: 23.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.2,
              gust_kph: 19.7,
              uv: 1,
            },
            {
              time_epoch: 1696888800,
              time: '2023-10-10 01:00',
              temp_c: 3.7,
              temp_f: 38.7,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 190,
              wind_dir: 'S',
              pressure_mb: 1022,
              pressure_in: 30.19,
              precip_mm: 0,
              precip_in: 0,
              humidity: 54,
              cloud: 43,
              feelslike_c: 1.1,
              feelslike_f: 34,
              windchill_c: 1.1,
              windchill_f: 34,
              heatindex_c: 3.7,
              heatindex_f: 38.7,
              dewpoint_c: -4.7,
              dewpoint_f: 23.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.2,
              gust_kph: 21.2,
              uv: 1,
            },
            {
              time_epoch: 1696892400,
              time: '2023-10-10 02:00',
              temp_c: 4.3,
              temp_f: 39.7,
              is_day: 0,
              condition: {
                text: 'Cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
                code: 1006,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 184,
              wind_dir: 'S',
              pressure_mb: 1022,
              pressure_in: 30.17,
              precip_mm: 0,
              precip_in: 0,
              humidity: 53,
              cloud: 84,
              feelslike_c: 1.7,
              feelslike_f: 35,
              windchill_c: 1.7,
              windchill_f: 35,
              heatindex_c: 4.3,
              heatindex_f: 39.7,
              dewpoint_c: -4.5,
              dewpoint_f: 23.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.2,
              gust_kph: 21.2,
              uv: 1,
            },
            {
              time_epoch: 1696896000,
              time: '2023-10-10 03:00',
              temp_c: 4.5,
              temp_f: 40.1,
              is_day: 0,
              condition: {
                text: 'Cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
                code: 1006,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 179,
              wind_dir: 'S',
              pressure_mb: 1021,
              pressure_in: 30.15,
              precip_mm: 0,
              precip_in: 0,
              humidity: 53,
              cloud: 84,
              feelslike_c: 1.8,
              feelslike_f: 35.3,
              windchill_c: 1.8,
              windchill_f: 35.3,
              heatindex_c: 4.5,
              heatindex_f: 40.1,
              dewpoint_c: -4.3,
              dewpoint_f: 24.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.7,
              gust_kph: 22.1,
              uv: 1,
            },
            {
              time_epoch: 1696899600,
              time: '2023-10-10 04:00',
              temp_c: 4.7,
              temp_f: 40.4,
              is_day: 0,
              condition: {
                text: 'Cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
                code: 1006,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 181,
              wind_dir: 'S',
              pressure_mb: 1020,
              pressure_in: 30.13,
              precip_mm: 0,
              precip_in: 0,
              humidity: 53,
              cloud: 80,
              feelslike_c: 1.9,
              feelslike_f: 35.4,
              windchill_c: 1.9,
              windchill_f: 35.4,
              heatindex_c: 4.7,
              heatindex_f: 40.4,
              dewpoint_c: -4,
              dewpoint_f: 24.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.6,
              gust_kph: 21.9,
              uv: 1,
            },
            {
              time_epoch: 1696903200,
              time: '2023-10-10 05:00',
              temp_c: 4.8,
              temp_f: 40.6,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 188,
              wind_dir: 'S',
              pressure_mb: 1020,
              pressure_in: 30.12,
              precip_mm: 0,
              precip_in: 0,
              humidity: 55,
              cloud: 32,
              feelslike_c: 1.5,
              feelslike_f: 34.6,
              windchill_c: 1.5,
              windchill_f: 34.6,
              heatindex_c: 4.8,
              heatindex_f: 40.6,
              dewpoint_c: -3.4,
              dewpoint_f: 25.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.4,
              gust_kph: 26.3,
              uv: 1,
            },
            {
              time_epoch: 1696906800,
              time: '2023-10-10 06:00',
              temp_c: 4.4,
              temp_f: 40,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 8.9,
              wind_kph: 14.4,
              wind_degree: 202,
              wind_dir: 'SSW',
              pressure_mb: 1020,
              pressure_in: 30.12,
              precip_mm: 0,
              precip_in: 0,
              humidity: 59,
              cloud: 28,
              feelslike_c: 1.2,
              feelslike_f: 34.1,
              windchill_c: 1.2,
              windchill_f: 34.1,
              heatindex_c: 4.4,
              heatindex_f: 40,
              dewpoint_c: -2.8,
              dewpoint_f: 26.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.6,
              gust_kph: 25.1,
              uv: 1,
            },
            {
              time_epoch: 1696910400,
              time: '2023-10-10 07:00',
              temp_c: 4.2,
              temp_f: 39.6,
              is_day: 0,
              condition: {
                text: 'Cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
                code: 1006,
              },
              wind_mph: 7.8,
              wind_kph: 12.6,
              wind_degree: 202,
              wind_dir: 'SSW',
              pressure_mb: 1019,
              pressure_in: 30.1,
              precip_mm: 0,
              precip_in: 0,
              humidity: 66,
              cloud: 83,
              feelslike_c: 1.2,
              feelslike_f: 34.2,
              windchill_c: 1.2,
              windchill_f: 34.2,
              heatindex_c: 4.2,
              heatindex_f: 39.6,
              dewpoint_c: -1.6,
              dewpoint_f: 29.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.4,
              gust_kph: 21.5,
              uv: 1,
            },
            {
              time_epoch: 1696914000,
              time: '2023-10-10 08:00',
              temp_c: 5.7,
              temp_f: 42.2,
              is_day: 1,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 203,
              wind_dir: 'SSW',
              pressure_mb: 1019,
              pressure_in: 30.09,
              precip_mm: 0.01,
              precip_in: 0,
              humidity: 67,
              cloud: 100,
              feelslike_c: 2.8,
              feelslike_f: 37.1,
              windchill_c: 2.8,
              windchill_f: 37.1,
              heatindex_c: 5.7,
              heatindex_f: 42.2,
              dewpoint_c: 0.1,
              dewpoint_f: 32.3,
              will_it_rain: 0,
              chance_of_rain: 62,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.1,
              gust_kph: 17.8,
              uv: 2,
            },
            {
              time_epoch: 1696917600,
              time: '2023-10-10 09:00',
              temp_c: 5.3,
              temp_f: 41.6,
              is_day: 1,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 8.7,
              wind_kph: 14,
              wind_degree: 199,
              wind_dir: 'SSW',
              pressure_mb: 1019,
              pressure_in: 30.1,
              precip_mm: 0.08,
              precip_in: 0,
              humidity: 76,
              cloud: 100,
              feelslike_c: 2.3,
              feelslike_f: 36.1,
              windchill_c: 2.3,
              windchill_f: 36.1,
              heatindex_c: 5.3,
              heatindex_f: 41.6,
              dewpoint_c: 1.4,
              dewpoint_f: 34.6,
              will_it_rain: 1,
              chance_of_rain: 87,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.8,
              gust_kph: 19,
              uv: 2,
            },
            {
              time_epoch: 1696921200,
              time: '2023-10-10 10:00',
              temp_c: 5.1,
              temp_f: 41.2,
              is_day: 1,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 8.7,
              wind_kph: 14,
              wind_degree: 193,
              wind_dir: 'SSW',
              pressure_mb: 1019,
              pressure_in: 30.09,
              precip_mm: 0.1,
              precip_in: 0,
              humidity: 81,
              cloud: 100,
              feelslike_c: 2,
              feelslike_f: 35.6,
              windchill_c: 2,
              windchill_f: 35.6,
              heatindex_c: 5.1,
              heatindex_f: 41.2,
              dewpoint_c: 2.1,
              dewpoint_f: 35.7,
              will_it_rain: 0,
              chance_of_rain: 65,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.1,
              gust_kph: 19.5,
              uv: 2,
            },
            {
              time_epoch: 1696924800,
              time: '2023-10-10 11:00',
              temp_c: 5.2,
              temp_f: 41.4,
              is_day: 1,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 194,
              wind_dir: 'SSW',
              pressure_mb: 1019,
              pressure_in: 30.09,
              precip_mm: 0.14,
              precip_in: 0.01,
              humidity: 83,
              cloud: 100,
              feelslike_c: 2,
              feelslike_f: 35.6,
              windchill_c: 2,
              windchill_f: 35.6,
              heatindex_c: 5.2,
              heatindex_f: 41.4,
              dewpoint_c: 2.6,
              dewpoint_f: 36.7,
              will_it_rain: 0,
              chance_of_rain: 65,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.1,
              gust_kph: 21.1,
              uv: 2,
            },
            {
              time_epoch: 1696928400,
              time: '2023-10-10 12:00',
              temp_c: 5.3,
              temp_f: 41.6,
              is_day: 1,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 196,
              wind_dir: 'SSW',
              pressure_mb: 1019,
              pressure_in: 30.08,
              precip_mm: 0.11,
              precip_in: 0,
              humidity: 85,
              cloud: 100,
              feelslike_c: 2.1,
              feelslike_f: 35.8,
              windchill_c: 2.1,
              windchill_f: 35.8,
              heatindex_c: 5.3,
              heatindex_f: 41.6,
              dewpoint_c: 3,
              dewpoint_f: 37.4,
              will_it_rain: 0,
              chance_of_rain: 65,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.1,
              gust_kph: 21.1,
              uv: 2,
            },
            {
              time_epoch: 1696932000,
              time: '2023-10-10 13:00',
              temp_c: 5.4,
              temp_f: 41.7,
              is_day: 1,
              condition: {
                text: 'Light drizzle',
                icon: '//cdn.weatherapi.com/weather/64x64/day/266.png',
                code: 1153,
              },
              wind_mph: 9.2,
              wind_kph: 14.8,
              wind_degree: 201,
              wind_dir: 'SSW',
              pressure_mb: 1018,
              pressure_in: 30.07,
              precip_mm: 0.3,
              precip_in: 0.01,
              humidity: 87,
              cloud: 100,
              feelslike_c: 2.3,
              feelslike_f: 36.1,
              windchill_c: 2.3,
              windchill_f: 36.1,
              heatindex_c: 5.4,
              heatindex_f: 41.7,
              dewpoint_c: 3.5,
              dewpoint_f: 38.2,
              will_it_rain: 0,
              chance_of_rain: 51,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 12.9,
              gust_kph: 20.7,
              uv: 2,
            },
            {
              time_epoch: 1696935600,
              time: '2023-10-10 14:00',
              temp_c: 5.4,
              temp_f: 41.8,
              is_day: 1,
              condition: {
                text: 'Light drizzle',
                icon: '//cdn.weatherapi.com/weather/64x64/day/266.png',
                code: 1153,
              },
              wind_mph: 8.7,
              wind_kph: 14,
              wind_degree: 205,
              wind_dir: 'SSW',
              pressure_mb: 1018,
              pressure_in: 30.07,
              precip_mm: 0.27,
              precip_in: 0.01,
              humidity: 90,
              cloud: 100,
              feelslike_c: 2.4,
              feelslike_f: 36.4,
              windchill_c: 2.4,
              windchill_f: 36.4,
              heatindex_c: 5.4,
              heatindex_f: 41.8,
              dewpoint_c: 4,
              dewpoint_f: 39.2,
              will_it_rain: 0,
              chance_of_rain: 55,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 12.6,
              gust_kph: 20.2,
              uv: 2,
            },
            {
              time_epoch: 1696939200,
              time: '2023-10-10 15:00',
              temp_c: 5.8,
              temp_f: 42.4,
              is_day: 1,
              condition: {
                text: 'Light drizzle',
                icon: '//cdn.weatherapi.com/weather/64x64/day/266.png',
                code: 1153,
              },
              wind_mph: 8.9,
              wind_kph: 14.4,
              wind_degree: 210,
              wind_dir: 'SSW',
              pressure_mb: 1018,
              pressure_in: 30.06,
              precip_mm: 0.32,
              precip_in: 0.01,
              humidity: 91,
              cloud: 100,
              feelslike_c: 2.8,
              feelslike_f: 37,
              windchill_c: 2.8,
              windchill_f: 37,
              heatindex_c: 5.8,
              heatindex_f: 42.4,
              dewpoint_c: 4.4,
              dewpoint_f: 39.9,
              will_it_rain: 0,
              chance_of_rain: 55,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 13,
              gust_kph: 20.9,
              uv: 2,
            },
            {
              time_epoch: 1696942800,
              time: '2023-10-10 16:00',
              temp_c: 6.1,
              temp_f: 43,
              is_day: 1,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 215,
              wind_dir: 'SW',
              pressure_mb: 1018,
              pressure_in: 30.06,
              precip_mm: 0.07,
              precip_in: 0,
              humidity: 89,
              cloud: 100,
              feelslike_c: 3,
              feelslike_f: 37.5,
              windchill_c: 3,
              windchill_f: 37.5,
              heatindex_c: 6.1,
              heatindex_f: 43,
              dewpoint_c: 4.4,
              dewpoint_f: 40,
              will_it_rain: 1,
              chance_of_rain: 87,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.3,
              gust_kph: 23,
              uv: 2,
            },
            {
              time_epoch: 1696946400,
              time: '2023-10-10 17:00',
              temp_c: 6.2,
              temp_f: 43.1,
              is_day: 1,
              condition: {
                text: 'Light drizzle',
                icon: '//cdn.weatherapi.com/weather/64x64/day/266.png',
                code: 1153,
              },
              wind_mph: 9.8,
              wind_kph: 15.8,
              wind_degree: 221,
              wind_dir: 'SW',
              pressure_mb: 1018,
              pressure_in: 30.06,
              precip_mm: 0.33,
              precip_in: 0.01,
              humidity: 91,
              cloud: 100,
              feelslike_c: 3.1,
              feelslike_f: 37.6,
              windchill_c: 3.1,
              windchill_f: 37.6,
              heatindex_c: 6.2,
              heatindex_f: 43.1,
              dewpoint_c: 4.9,
              dewpoint_f: 40.8,
              will_it_rain: 0,
              chance_of_rain: 62,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 14.7,
              gust_kph: 23.7,
              uv: 2,
            },
            {
              time_epoch: 1696950000,
              time: '2023-10-10 18:00',
              temp_c: 6.7,
              temp_f: 44.1,
              is_day: 1,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 10.3,
              wind_kph: 16.6,
              wind_degree: 231,
              wind_dir: 'SW',
              pressure_mb: 1018,
              pressure_in: 30.07,
              precip_mm: 0.01,
              precip_in: 0,
              humidity: 92,
              cloud: 100,
              feelslike_c: 3.7,
              feelslike_f: 38.6,
              windchill_c: 3.7,
              windchill_f: 38.6,
              heatindex_c: 6.7,
              heatindex_f: 44.1,
              dewpoint_c: 5.4,
              dewpoint_f: 41.8,
              will_it_rain: 0,
              chance_of_rain: 64,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.3,
              gust_kph: 26.2,
              uv: 2,
            },
            {
              time_epoch: 1696953600,
              time: '2023-10-10 19:00',
              temp_c: 7.3,
              temp_f: 45.1,
              is_day: 0,
              condition: {
                text: 'Light drizzle',
                icon: '//cdn.weatherapi.com/weather/64x64/night/266.png',
                code: 1153,
              },
              wind_mph: 10.1,
              wind_kph: 16.2,
              wind_degree: 239,
              wind_dir: 'WSW',
              pressure_mb: 1018,
              pressure_in: 30.08,
              precip_mm: 0.33,
              precip_in: 0.01,
              humidity: 93,
              cloud: 100,
              feelslike_c: 4.4,
              feelslike_f: 39.9,
              windchill_c: 4.4,
              windchill_f: 39.9,
              heatindex_c: 7.3,
              heatindex_f: 45.1,
              dewpoint_c: 6.2,
              dewpoint_f: 43.2,
              will_it_rain: 0,
              chance_of_rain: 55,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 16,
              gust_kph: 25.7,
              uv: 1,
            },
            {
              time_epoch: 1696957200,
              time: '2023-10-10 20:00',
              temp_c: 7.6,
              temp_f: 45.6,
              is_day: 0,
              condition: {
                text: 'Light drizzle',
                icon: '//cdn.weatherapi.com/weather/64x64/night/266.png',
                code: 1153,
              },
              wind_mph: 10.1,
              wind_kph: 16.2,
              wind_degree: 241,
              wind_dir: 'WSW',
              pressure_mb: 1019,
              pressure_in: 30.08,
              precip_mm: 0.16,
              precip_in: 0.01,
              humidity: 94,
              cloud: 100,
              feelslike_c: 4.7,
              feelslike_f: 40.5,
              windchill_c: 4.7,
              windchill_f: 40.5,
              heatindex_c: 7.6,
              heatindex_f: 45.6,
              dewpoint_c: 6.6,
              dewpoint_f: 43.9,
              will_it_rain: 0,
              chance_of_rain: 61,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 15.9,
              gust_kph: 25.7,
              uv: 1,
            },
            {
              time_epoch: 1696960800,
              time: '2023-10-10 21:00',
              temp_c: 8.3,
              temp_f: 46.9,
              is_day: 0,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
                code: 1009,
              },
              wind_mph: 11.6,
              wind_kph: 18.7,
              wind_degree: 249,
              wind_dir: 'WSW',
              pressure_mb: 1019,
              pressure_in: 30.08,
              precip_mm: 0,
              precip_in: 0,
              humidity: 90,
              cloud: 95,
              feelslike_c: 5.3,
              feelslike_f: 41.6,
              windchill_c: 5.3,
              windchill_f: 41.6,
              heatindex_c: 8.3,
              heatindex_f: 46.9,
              dewpoint_c: 6.7,
              dewpoint_f: 44.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 18,
              gust_kph: 28.9,
              uv: 1,
            },
            {
              time_epoch: 1696964400,
              time: '2023-10-10 22:00',
              temp_c: 8.4,
              temp_f: 47.1,
              is_day: 0,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
                code: 1063,
              },
              wind_mph: 12.3,
              wind_kph: 19.8,
              wind_degree: 253,
              wind_dir: 'WSW',
              pressure_mb: 1019,
              pressure_in: 30.09,
              precip_mm: 0.08,
              precip_in: 0,
              humidity: 90,
              cloud: 94,
              feelslike_c: 5.4,
              feelslike_f: 41.7,
              windchill_c: 5.4,
              windchill_f: 41.7,
              heatindex_c: 8.4,
              heatindex_f: 47.1,
              dewpoint_c: 6.9,
              dewpoint_f: 44.4,
              will_it_rain: 0,
              chance_of_rain: 63,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.2,
              gust_kph: 30.9,
              uv: 1,
            },
            {
              time_epoch: 1696968000,
              time: '2023-10-10 23:00',
              temp_c: 8.6,
              temp_f: 47.4,
              is_day: 0,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
                code: 1063,
              },
              wind_mph: 12.5,
              wind_kph: 20.2,
              wind_degree: 254,
              wind_dir: 'WSW',
              pressure_mb: 1019,
              pressure_in: 30.09,
              precip_mm: 0.02,
              precip_in: 0,
              humidity: 91,
              cloud: 73,
              feelslike_c: 5.5,
              feelslike_f: 42,
              windchill_c: 5.5,
              windchill_f: 42,
              heatindex_c: 8.6,
              heatindex_f: 47.4,
              dewpoint_c: 7.2,
              dewpoint_f: 44.9,
              will_it_rain: 1,
              chance_of_rain: 76,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.7,
              gust_kph: 31.7,
              uv: 1,
            },
          ],
        },
        {
          date: '2023-10-11',
          date_epoch: 1696982400,
          day: {
            maxtemp_c: 17.2,
            maxtemp_f: 63,
            mintemp_c: 6.4,
            mintemp_f: 43.4,
            avgtemp_c: 10,
            avgtemp_f: 50,
            maxwind_mph: 16.3,
            maxwind_kph: 26.3,
            totalprecip_mm: 0.01,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 83,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            uv: 4,
          },
          astro: {
            sunrise: '07:39 AM',
            sunset: '06:42 PM',
            moonrise: '03:43 AM',
            moonset: '05:55 PM',
            moon_phase: 'Waning Crescent',
            moon_illumination: '13',
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1696971600,
              time: '2023-10-11 00:00',
              temp_c: 8.7,
              temp_f: 47.6,
              is_day: 0,
              condition: {
                text: 'Patchy rain possible',
                icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
                code: 1063,
              },
              wind_mph: 13.2,
              wind_kph: 21.2,
              wind_degree: 253,
              wind_dir: 'WSW',
              pressure_mb: 1019,
              pressure_in: 30.09,
              precip_mm: 0.01,
              precip_in: 0,
              humidity: 91,
              cloud: 51,
              feelslike_c: 5.6,
              feelslike_f: 42,
              windchill_c: 5.6,
              windchill_f: 42,
              heatindex_c: 8.7,
              heatindex_f: 47.6,
              dewpoint_c: 7.2,
              dewpoint_f: 45,
              will_it_rain: 0,
              chance_of_rain: 62,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.7,
              gust_kph: 33.3,
              uv: 1,
            },
            {
              time_epoch: 1696975200,
              time: '2023-10-11 01:00',
              temp_c: 8.6,
              temp_f: 47.5,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 12.8,
              wind_kph: 20.5,
              wind_degree: 257,
              wind_dir: 'WSW',
              pressure_mb: 1019,
              pressure_in: 30.1,
              precip_mm: 0,
              precip_in: 0,
              humidity: 90,
              cloud: 32,
              feelslike_c: 5.6,
              feelslike_f: 42,
              windchill_c: 5.6,
              windchill_f: 42,
              heatindex_c: 8.6,
              heatindex_f: 47.5,
              dewpoint_c: 7.1,
              dewpoint_f: 44.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.7,
              gust_kph: 33.4,
              uv: 1,
            },
            {
              time_epoch: 1696978800,
              time: '2023-10-11 02:00',
              temp_c: 7.4,
              temp_f: 45.4,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 11.4,
              wind_kph: 18.4,
              wind_degree: 254,
              wind_dir: 'WSW',
              pressure_mb: 1019,
              pressure_in: 30.1,
              precip_mm: 0,
              precip_in: 0,
              humidity: 93,
              cloud: 25,
              feelslike_c: 4.3,
              feelslike_f: 39.8,
              windchill_c: 4.3,
              windchill_f: 39.8,
              heatindex_c: 7.4,
              heatindex_f: 45.4,
              dewpoint_c: 6.3,
              dewpoint_f: 43.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 21.7,
              gust_kph: 34.8,
              uv: 1,
            },
            {
              time_epoch: 1696982400,
              time: '2023-10-11 03:00',
              temp_c: 7,
              temp_f: 44.6,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 10.3,
              wind_kph: 16.6,
              wind_degree: 248,
              wind_dir: 'WSW',
              pressure_mb: 1019,
              pressure_in: 30.1,
              precip_mm: 0,
              precip_in: 0,
              humidity: 93,
              cloud: 28,
              feelslike_c: 4,
              feelslike_f: 39.3,
              windchill_c: 4,
              windchill_f: 39.3,
              heatindex_c: 7,
              heatindex_f: 44.6,
              dewpoint_c: 5.9,
              dewpoint_f: 42.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.3,
              gust_kph: 32.6,
              uv: 1,
            },
            {
              time_epoch: 1696986000,
              time: '2023-10-11 04:00',
              temp_c: 7,
              temp_f: 44.6,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 10.1,
              wind_kph: 16.2,
              wind_degree: 240,
              wind_dir: 'WSW',
              pressure_mb: 1019,
              pressure_in: 30.09,
              precip_mm: 0,
              precip_in: 0,
              humidity: 93,
              cloud: 24,
              feelslike_c: 4,
              feelslike_f: 39.3,
              windchill_c: 4,
              windchill_f: 39.3,
              heatindex_c: 7,
              heatindex_f: 44.6,
              dewpoint_c: 5.9,
              dewpoint_f: 42.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.6,
              gust_kph: 31.6,
              uv: 1,
            },
            {
              time_epoch: 1696989600,
              time: '2023-10-11 05:00',
              temp_c: 6.5,
              temp_f: 43.7,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 9.8,
              wind_kph: 15.8,
              wind_degree: 236,
              wind_dir: 'WSW',
              pressure_mb: 1019,
              pressure_in: 30.09,
              precip_mm: 0,
              precip_in: 0,
              humidity: 93,
              cloud: 50,
              feelslike_c: 3.5,
              feelslike_f: 38.2,
              windchill_c: 3.5,
              windchill_f: 38.2,
              heatindex_c: 6.5,
              heatindex_f: 43.7,
              dewpoint_c: 5.4,
              dewpoint_f: 41.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.9,
              gust_kph: 32,
              uv: 1,
            },
            {
              time_epoch: 1696993200,
              time: '2023-10-11 06:00',
              temp_c: 6.4,
              temp_f: 43.4,
              is_day: 0,
              condition: {
                text: 'Cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
                code: 1006,
              },
              wind_mph: 10.7,
              wind_kph: 17.3,
              wind_degree: 232,
              wind_dir: 'SW',
              pressure_mb: 1019,
              pressure_in: 30.08,
              precip_mm: 0,
              precip_in: 0,
              humidity: 92,
              cloud: 80,
              feelslike_c: 3.1,
              feelslike_f: 37.6,
              windchill_c: 3.1,
              windchill_f: 37.6,
              heatindex_c: 6.4,
              heatindex_f: 43.4,
              dewpoint_c: 5.2,
              dewpoint_f: 41.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 21.4,
              gust_kph: 34.4,
              uv: 1,
            },
            {
              time_epoch: 1696996800,
              time: '2023-10-11 07:00',
              temp_c: 6.5,
              temp_f: 43.8,
              is_day: 0,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 11.2,
              wind_kph: 18,
              wind_degree: 228,
              wind_dir: 'SW',
              pressure_mb: 1018,
              pressure_in: 30.07,
              precip_mm: 0,
              precip_in: 0,
              humidity: 92,
              cloud: 47,
              feelslike_c: 3.2,
              feelslike_f: 37.8,
              windchill_c: 3.2,
              windchill_f: 37.8,
              heatindex_c: 6.5,
              heatindex_f: 43.8,
              dewpoint_c: 5.3,
              dewpoint_f: 41.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 22.2,
              gust_kph: 35.8,
              uv: 1,
            },
            {
              time_epoch: 1697000400,
              time: '2023-10-11 08:00',
              temp_c: 8.2,
              temp_f: 46.8,
              is_day: 1,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 12.3,
              wind_kph: 19.8,
              wind_degree: 226,
              wind_dir: 'SW',
              pressure_mb: 1018,
              pressure_in: 30.07,
              precip_mm: 0,
              precip_in: 0,
              humidity: 87,
              cloud: 39,
              feelslike_c: 5.2,
              feelslike_f: 41.3,
              windchill_c: 5.2,
              windchill_f: 41.3,
              heatindex_c: 8.2,
              heatindex_f: 46.8,
              dewpoint_c: 6.2,
              dewpoint_f: 43.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 21.3,
              gust_kph: 34.2,
              uv: 3,
            },
            {
              time_epoch: 1697004000,
              time: '2023-10-11 09:00',
              temp_c: 10.5,
              temp_f: 50.9,
              is_day: 1,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 13.4,
              wind_kph: 21.6,
              wind_degree: 227,
              wind_dir: 'SW',
              pressure_mb: 1018,
              pressure_in: 30.06,
              precip_mm: 0,
              precip_in: 0,
              humidity: 80,
              cloud: 45,
              feelslike_c: 8.4,
              feelslike_f: 47.1,
              windchill_c: 8.4,
              windchill_f: 47.1,
              heatindex_c: 10.5,
              heatindex_f: 50.9,
              dewpoint_c: 7,
              dewpoint_f: 44.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.8,
              gust_kph: 33.5,
              uv: 4,
            },
            {
              time_epoch: 1697007600,
              time: '2023-10-11 10:00',
              temp_c: 12.8,
              temp_f: 55,
              is_day: 1,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 14.8,
              wind_kph: 23.8,
              wind_degree: 229,
              wind_dir: 'SW',
              pressure_mb: 1017,
              pressure_in: 30.04,
              precip_mm: 0,
              precip_in: 0,
              humidity: 73,
              cloud: 51,
              feelslike_c: 11.7,
              feelslike_f: 53.1,
              windchill_c: 11.7,
              windchill_f: 53.1,
              heatindex_c: 12.8,
              heatindex_f: 55,
              dewpoint_c: 7.8,
              dewpoint_f: 46,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.4,
              gust_kph: 32.8,
              uv: 4,
            },
            {
              time_epoch: 1697011200,
              time: '2023-10-11 11:00',
              temp_c: 15,
              temp_f: 59,
              is_day: 1,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 15.9,
              wind_kph: 25.6,
              wind_degree: 231,
              wind_dir: 'SW',
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              humidity: 66,
              cloud: 57,
              feelslike_c: 15,
              feelslike_f: 59,
              windchill_c: 15,
              windchill_f: 59,
              heatindex_c: 15,
              heatindex_f: 59,
              dewpoint_c: 8.7,
              dewpoint_f: 47.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.8,
              gust_kph: 31.9,
              uv: 5,
            },
            {
              time_epoch: 1697014800,
              time: '2023-10-11 12:00',
              temp_c: 15.8,
              temp_f: 60.4,
              is_day: 1,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 16.1,
              wind_kph: 25.9,
              wind_degree: 232,
              wind_dir: 'SW',
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 63,
              cloud: 41,
              feelslike_c: 15.8,
              feelslike_f: 60.4,
              windchill_c: 15.8,
              windchill_f: 60.4,
              heatindex_c: 15.8,
              heatindex_f: 60.4,
              dewpoint_c: 8.8,
              dewpoint_f: 47.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.1,
              gust_kph: 32.4,
              uv: 5,
            },
            {
              time_epoch: 1697018400,
              time: '2023-10-11 13:00',
              temp_c: 16.5,
              temp_f: 61.7,
              is_day: 1,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 16.1,
              wind_kph: 25.9,
              wind_degree: 234,
              wind_dir: 'SW',
              pressure_mb: 1016,
              pressure_in: 30,
              precip_mm: 0,
              precip_in: 0,
              humidity: 61,
              cloud: 25,
              feelslike_c: 16.5,
              feelslike_f: 61.7,
              windchill_c: 16.5,
              windchill_f: 61.7,
              heatindex_c: 16.5,
              heatindex_f: 61.7,
              dewpoint_c: 8.9,
              dewpoint_f: 48,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.4,
              gust_kph: 32.8,
              uv: 5,
            },
            {
              time_epoch: 1697022000,
              time: '2023-10-11 14:00',
              temp_c: 17.2,
              temp_f: 63,
              is_day: 1,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 16.3,
              wind_kph: 26.3,
              wind_degree: 236,
              wind_dir: 'WSW',
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0,
              precip_in: 0,
              humidity: 59,
              cloud: 10,
              feelslike_c: 17.2,
              feelslike_f: 63,
              windchill_c: 17.2,
              windchill_f: 63,
              heatindex_c: 17.2,
              heatindex_f: 63,
              dewpoint_c: 9.1,
              dewpoint_f: 48.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.6,
              gust_kph: 33.1,
              uv: 5,
            },
            {
              time_epoch: 1697025600,
              time: '2023-10-11 15:00',
              temp_c: 16.6,
              temp_f: 61.9,
              is_day: 1,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 16.1,
              wind_kph: 25.9,
              wind_degree: 235,
              wind_dir: 'SW',
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0,
              precip_in: 0,
              humidity: 61,
              cloud: 12,
              feelslike_c: 16.6,
              feelslike_f: 61.9,
              windchill_c: 16.6,
              windchill_f: 61.9,
              heatindex_c: 16.6,
              heatindex_f: 61.9,
              dewpoint_c: 9.1,
              dewpoint_f: 48.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 21.9,
              gust_kph: 35.3,
              uv: 5,
            },
            {
              time_epoch: 1697029200,
              time: '2023-10-11 16:00',
              temp_c: 16,
              temp_f: 60.8,
              is_day: 1,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 16.1,
              wind_kph: 25.9,
              wind_degree: 235,
              wind_dir: 'SW',
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0,
              precip_in: 0,
              humidity: 63,
              cloud: 13,
              feelslike_c: 16,
              feelslike_f: 60.8,
              windchill_c: 16,
              windchill_f: 60.8,
              heatindex_c: 16,
              heatindex_f: 60.8,
              dewpoint_c: 9.1,
              dewpoint_f: 48.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 23.3,
              gust_kph: 37.4,
              uv: 5,
            },
            {
              time_epoch: 1697032800,
              time: '2023-10-11 17:00',
              temp_c: 15.4,
              temp_f: 59.7,
              is_day: 1,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 15.9,
              wind_kph: 25.6,
              wind_degree: 234,
              wind_dir: 'SW',
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0,
              precip_in: 0,
              humidity: 66,
              cloud: 15,
              feelslike_c: 15.4,
              feelslike_f: 59.7,
              windchill_c: 15.4,
              windchill_f: 59.7,
              heatindex_c: 15.4,
              heatindex_f: 59.7,
              dewpoint_c: 9.1,
              dewpoint_f: 48.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 24.5,
              gust_kph: 39.5,
              uv: 5,
            },
            {
              time_epoch: 1697036400,
              time: '2023-10-11 18:00',
              temp_c: 14.5,
              temp_f: 58.1,
              is_day: 1,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 15.7,
              wind_kph: 25.2,
              wind_degree: 234,
              wind_dir: 'SW',
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0,
              precip_in: 0,
              humidity: 69,
              cloud: 14,
              feelslike_c: 13.7,
              feelslike_f: 56.7,
              windchill_c: 13.7,
              windchill_f: 56.7,
              heatindex_c: 14.5,
              heatindex_f: 58.1,
              dewpoint_c: 8.8,
              dewpoint_f: 47.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 25.5,
              gust_kph: 41,
              uv: 4,
            },
            {
              time_epoch: 1697040000,
              time: '2023-10-11 19:00',
              temp_c: 13.6,
              temp_f: 56.5,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 15.7,
              wind_kph: 25.2,
              wind_degree: 234,
              wind_dir: 'SW',
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0,
              precip_in: 0,
              humidity: 71,
              cloud: 14,
              feelslike_c: 12,
              feelslike_f: 53.6,
              windchill_c: 12,
              windchill_f: 53.6,
              heatindex_c: 13.6,
              heatindex_f: 56.5,
              dewpoint_c: 8.5,
              dewpoint_f: 47.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 26.6,
              gust_kph: 42.8,
              uv: 1,
            },
            {
              time_epoch: 1697043600,
              time: '2023-10-11 20:00',
              temp_c: 12.7,
              temp_f: 54.8,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 15.4,
              wind_kph: 24.8,
              wind_degree: 234,
              wind_dir: 'SW',
              pressure_mb: 1015,
              pressure_in: 29.99,
              precip_mm: 0,
              precip_in: 0,
              humidity: 74,
              cloud: 13,
              feelslike_c: 10.4,
              feelslike_f: 50.7,
              windchill_c: 10.4,
              windchill_f: 50.7,
              heatindex_c: 12.7,
              heatindex_f: 54.8,
              dewpoint_c: 8.2,
              dewpoint_f: 46.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 27.5,
              gust_kph: 44.3,
              uv: 1,
            },
            {
              time_epoch: 1697047200,
              time: '2023-10-11 21:00',
              temp_c: 13,
              temp_f: 55.4,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 15.2,
              wind_kph: 24.5,
              wind_degree: 232,
              wind_dir: 'SW',
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0,
              precip_in: 0,
              humidity: 73,
              cloud: 10,
              feelslike_c: 10.8,
              feelslike_f: 51.4,
              windchill_c: 10.8,
              windchill_f: 51.4,
              heatindex_c: 13,
              heatindex_f: 55.4,
              dewpoint_c: 8.3,
              dewpoint_f: 46.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 27.7,
              gust_kph: 44.6,
              uv: 1,
            },
            {
              time_epoch: 1697050800,
              time: '2023-10-11 22:00',
              temp_c: 13.3,
              temp_f: 55.9,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 15.2,
              wind_kph: 24.5,
              wind_degree: 230,
              wind_dir: 'SW',
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0,
              precip_in: 0,
              humidity: 72,
              cloud: 6,
              feelslike_c: 11.3,
              feelslike_f: 52.3,
              windchill_c: 11.3,
              windchill_f: 52.3,
              heatindex_c: 13.3,
              heatindex_f: 55.9,
              dewpoint_c: 8.5,
              dewpoint_f: 47.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 27.7,
              gust_kph: 44.6,
              uv: 1,
            },
            {
              time_epoch: 1697054400,
              time: '2023-10-11 23:00',
              temp_c: 13.7,
              temp_f: 56.6,
              is_day: 0,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 15,
              wind_kph: 24.1,
              wind_degree: 228,
              wind_dir: 'SW',
              pressure_mb: 1015,
              pressure_in: 29.97,
              precip_mm: 0,
              precip_in: 0,
              humidity: 71,
              cloud: 3,
              feelslike_c: 11.7,
              feelslike_f: 53.1,
              windchill_c: 11.7,
              windchill_f: 53.1,
              heatindex_c: 13.7,
              heatindex_f: 56.6,
              dewpoint_c: 8.6,
              dewpoint_f: 47.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 28,
              gust_kph: 45,
              uv: 1,
            },
          ],
        },
      ],
    },
  };
  return {
    comments,
    AuthorsInstagram,
    dropDowns,
    urls,
    categories,
    profileOptions,
    mockWeather,
    randomChartData: generateRandomChartData(10),
    members,
  };
}

export default useMockData;
